spring:
  application:
    name: greetings-kstream-springboot

  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  kafka:
    streams:
      application-id: greetings-kstream-springboot
      bootstrap-servers: localhost:9092

    properties:
      default:
        deserialization:
          exception:
            handler: com.springboot.kstream.greetings.exceptionhandler.CustomDeserializerExceptionHandler
            #handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
